import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='h-screen'>
      <body className={inter.className + "  flex flex-wrap justify-center content-center bg-red-900 h-full"}>{children}</body>
    </html>
  )
}
